export const NOTIFICATION_EVENTS = {
  LEAVE_APPLIED: "LEAVE_APPLIED",
  LEAVE_APPROVED: "LEAVE_APPROVED",
  LEAVE_REJECTED: "LEAVE_REJECTED",

  ATTENDANCE_CORRECTION_APPLIED: "ATTENDANCE_CORRECTION_APPLIED",
  ATTENDANCE_CORRECTION_APPROVED: "ATTENDANCE_CORRECTION_APPROVED",
  ATTENDANCE_CORRECTION_REJECTED: "ATTENDANCE_CORRECTION_REJECTED",

  PAYROLL_PROCESSED: "PAYROLL_PROCESSED",
  PAYROLL_LOCKED: "PAYROLL_LOCKED",

  PAYSLIP_GENERATED: "PAYSLIP_GENERATED",

  HOLIDAY_ADDED: "HOLIDAY_ADDED",

  ONBOARDING_REQUEST: "ONBOARDING_REQUEST",

  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_REASSIGNED: "TASK_REASSIGNED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_DUE_TODAY: "TASK_DUE_TODAY",
  TASK_OVERDUE: "TASK_OVERDUE",
};

export const NOTIFICATION_TYPES = {
  LEAVE: "leave",
  ATTENDANCE: "attendance",
  PAYROLL: "payroll",
  PAYSLIP: "payslip",
  HOLIDAY: "holiday",
  ONBOARDING: "onboarding",
  TASK: "task",
  SYSTEM: "system",
};