export const NOTIFICATION_EVENTS = {
  LEAVE_APPLIED: "LEAVE_APPLIED",
  LEAVE_APPROVED: "LEAVE_APPROVED",
  LEAVE_REJECTED: "LEAVE_REJECTED",

  ATTENDANCE_CORRECTION_APPLIED: "ATTENDANCE_CORRECTION_APPLIED",
  ATTENDANCE_CORRECTION_APPROVED: "ATTENDANCE_CORRECTION_APPROVED",
  ATTENDANCE_CORRECTION_REJECTED: "ATTENDANCE_CORRECTION_REJECTED",

  PAYROLL_PROCESSED: "PAYROLL_PROCESSED",
  PAYROLL_LOCKED: "PAYROLL_LOCKED",

  PAYSLIP_GENERATED: "PAYSLIP_GENERATED",

  HOLIDAY_ADDED: "HOLIDAY_ADDED",

  ONBOARDING_REQUEST: "ONBOARDING_REQUEST",

  /*
  | The exit journey. One event per hand-off rather than a single
  | RESIGNATION_UPDATED, because each one is addressed to a different person
  | and says a different thing: the manager is asked to decide, the employee
  | is asked to return a laptop, finance is asked to release money.
  */
  RESIGNATION_RAISED: "RESIGNATION_RAISED",
  RESIGNATION_MANAGER_APPROVED: "RESIGNATION_MANAGER_APPROVED",
  RESIGNATION_REJECTED: "RESIGNATION_REJECTED",
  RESIGNATION_EQUIPMENT_REQUESTED: "RESIGNATION_EQUIPMENT_REQUESTED",
  RESIGNATION_EQUIPMENT_SUBMITTED: "RESIGNATION_EQUIPMENT_SUBMITTED",
  RESIGNATION_FNF_RETURNED: "RESIGNATION_FNF_RETURNED",
  RESIGNATION_FNF_REVIEW: "RESIGNATION_FNF_REVIEW",
  RESIGNATION_FINANCE_PENDING: "RESIGNATION_FINANCE_PENDING",
  RESIGNATION_EXITED: "RESIGNATION_EXITED",

  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_REASSIGNED: "TASK_REASSIGNED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_DUE_TODAY: "TASK_DUE_TODAY",
  TASK_OVERDUE: "TASK_OVERDUE",
};

export const NOTIFICATION_TYPES = {
  LEAVE: "leave",
  ATTENDANCE: "attendance",
  PAYROLL: "payroll",
  PAYSLIP: "payslip",
  HOLIDAY: "holiday",
  ONBOARDING: "onboarding",
  RESIGNATION: "resignation",
  TASK: "task",
  SYSTEM: "system",
};